name: Deploy on Push

on: 
 - push
 - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.2
    - name: Setup Node
      uses: actions/setup-node@v4.0.2
    - name: Install dependencies
      working-directory: ./web-app
      run: npm install
    - name: Build Webapp
      working-directory: ./web-app
      run: npm run build

    - name: deploy file to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: 'root'
        server: 'secrets.146.190.39.218'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './web-app/build/*'
        remote_path: '/root/web-app'
        sftpArgs: '-o ConnectTimeout=5'
        
