name: Deploy on Push

on: 
  push:
   branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.2
    - name: Setup Node
      uses: actions/setup-node@v4.0.2
    - name: Install dependencies
      working-directory: ./web-app
      run: npm ci
    - name: Build Webapp
      working-directory: ./web-app
      run: npm run build

    - name: deploy web-app to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: 'root'
        server: '146.190.39.218'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './web-app/build/*'
        remote_path: '/root/web-app'
        sftpArgs: '-o ConnectTimeout=5'

    - name: deploy api to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: 'root'
        server: '146.190.39.218'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './api/*'
        remote_path: '/root/api'
        sftpArgs: '-o ConnectTimeout=5'
        
    - name: Redeploy API
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: '146.190.39.218'
        username: 'root'
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd api
          npm ci
          pm2 restart app-api
